#!/bin/bash
# ================================================================
#  IPTV Panel — server performance tuning (idempotent)
#  Sourced by install.sh and update.sh. Safe to run repeatedly.
#
#  1. Nginx http-block: ensure sendfile + tcp_nopush + tcp_nodelay on.
#     sendfile+tcp_nopush send full packets for .ts bodies; tcp_nodelay
#     flushes the last partial packet / small .m3u8 immediately instead
#     of waiting on Nagle — the recommended combo for HLS delivery.
#
#  2. /var/iptv/hls on tmpfs (RAM disk). FFmpeg writes and deletes
#     thousands of tiny segment files per second; serving them from RAM
#     removes disk IO latency. Sized to the box (min(2G, 40% RAM)); the
#     dir is ephemeral, so starting empty after a reboot is fine — the
#     panel regenerates segments on demand. Override with HLS_TMPFS_SIZE
#     (MB) or skip entirely with HLS_TMPFS_DISABLE=1.
#
#  3. Empty-segment guard: a systemd timer deletes ABANDONED 0-byte .ts
#     files (older than 15s) so a request for one 404s via nginx
#     try_files instead of serving an empty 200 that stalls players. The
#     15s floor never touches a segment FFmpeg is still writing.
#
#  njs note: a per-request njs size check was considered but njs is not
#  packaged for the distro nginx (Ubuntu 22.04 ships nginx 1.18 without
#  libnginx-mod-http-njs), so this sweep + try_files is the no-module
#  equivalent. Edge layer (Cloudflare Worker no-store on 0-byte) is
#  configured separately and complements this.
# ================================================================
set -uo pipefail

HLS_DIR="${HLS_DIR:-/var/iptv/hls}"
HLS_USER="${HLS_USER:-www-data}"
NGINX_CONF="${NGINX_CONF:-/etc/nginx/nginx.conf}"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info() { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }

# ── 1. Nginx http-block TCP options ──────────────────────────────
tune_nginx() {
    [[ -f "$NGINX_CONF" ]] || { warn "nginx.conf not found at $NGINX_CONF — skipping TCP tuning"; return; }
    local changed=0
    if ! grep -qE '^[[:space:]]*sendfile[[:space:]]+on;' "$NGINX_CONF"; then
        sed -i '0,/^[[:space:]]*http[[:space:]]*{/s//&\n\tsendfile on;/' "$NGINX_CONF" && changed=1
    fi
    if ! grep -qE '^[[:space:]]*tcp_nopush[[:space:]]+on;' "$NGINX_CONF"; then
        sed -i '0,/sendfile on;/s//sendfile on;\n\ttcp_nopush on;/' "$NGINX_CONF" && changed=1
    fi
    if ! grep -qE '^[[:space:]]*tcp_nodelay[[:space:]]+on;' "$NGINX_CONF"; then
        sed -i '0,/tcp_nopush on;/s//tcp_nopush on;\n\ttcp_nodelay on;/' "$NGINX_CONF" && changed=1
    fi
    if [[ "$changed" -eq 1 ]]; then
        if nginx -t >/dev/null 2>&1; then
            systemctl reload nginx >/dev/null 2>&1 || true
            info "nginx http TCP options ensured (sendfile/tcp_nopush/tcp_nodelay on)"
        else
            warn "nginx -t failed after TCP-option edit — review $NGINX_CONF"
        fi
    else
        info "nginx TCP options already present"
    fi
}

# ── 2. HLS on tmpfs (RAM disk) ───────────────────────────────────
setup_tmpfs() {
    if [[ "${HLS_TMPFS_DISABLE:-0}" == "1" ]]; then warn "HLS tmpfs disabled (HLS_TMPFS_DISABLE=1)"; return; fi
    mkdir -p "$HLS_DIR"
    if findmnt -no FSTYPE "$HLS_DIR" 2>/dev/null | grep -q tmpfs; then
        info "$HLS_DIR already on tmpfs"
    else
        local size_mb
        if [[ -n "${HLS_TMPFS_SIZE:-}" ]]; then
            size_mb="${HLS_TMPFS_SIZE}"
        else
            local ram_mb; ram_mb=$(free -m | awk '/^Mem:/{print $2}')
            size_mb=$(( ram_mb * 40 / 100 ))
            (( size_mb > 2048 )) && size_mb=2048
            (( size_mb < 512 ))  && size_mb=512
        fi
        local uidn gidn
        uidn=$(id -u "$HLS_USER" 2>/dev/null || echo 33)
        gidn=$(id -g "$HLS_USER" 2>/dev/null || echo 33)
        local line="tmpfs $HLS_DIR tmpfs defaults,size=${size_mb}M,mode=0755,uid=${uidn},gid=${gidn},noatime 0 0"
        if ! grep -qE "[[:space:]]${HLS_DIR}[[:space:]]+tmpfs" /etc/fstab; then
            printf '\n# IPTV Panel — HLS segments on RAM disk (ephemeral, regenerated by ffmpeg)\n%s\n' "$line" >> /etc/fstab
        fi
        # NOTE: never `fuser -km "$HLS_DIR"` here — before the mount exists that
        # resolves to the parent filesystem (/) and SIGKILLs the whole box. Open
        # read fds (nginx) do not block a mount-over; the caller restarts the
        # backend afterward so ffmpeg re-points onto the new tmpfs.
        if mount "$HLS_DIR" 2>/dev/null; then
            info "mounted $HLS_DIR on tmpfs (${size_mb}M)"
        else
            warn "could not mount $HLS_DIR as tmpfs now — fstab entry added, applies on reboot"
        fi
    fi
    chown "$HLS_USER":"$HLS_USER" "$HLS_DIR" 2>/dev/null || true
    chmod 755 "$HLS_DIR" 2>/dev/null || true
}

# ── 3. Empty-segment guard (systemd timer) ───────────────────────
setup_empty_guard() {
    cat > /usr/local/sbin/hls-clean-empty.sh <<EOF
#!/bin/sh
# Delete ABANDONED 0-byte HLS .ts segments (older than 15s) so a request for them
# 404s via nginx try_files. The 15s floor never deletes a segment ffmpeg is still
# writing (a segment is 0 bytes only briefly while being created).
find "$HLS_DIR" -type f -name '*.ts' -size 0 ! -newermt '-15 seconds' -delete 2>/dev/null
EOF
    chmod 0755 /usr/local/sbin/hls-clean-empty.sh

    cat > /etc/systemd/system/hls-clean-empty.service <<'EOF'
[Unit]
Description=Delete abandoned 0-byte HLS .ts segments (empty-segment 404 guard)
After=iptv-panel.service

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/hls-clean-empty.sh
Nice=10
IOSchedulingClass=idle
EOF

    cat > /etc/systemd/system/hls-clean-empty.timer <<'EOF'
[Unit]
Description=Run HLS empty-segment sweep every 10s

[Timer]
OnBootSec=30s
OnUnitActiveSec=10s
AccuracySec=1s
Unit=hls-clean-empty.service

[Install]
WantedBy=timers.target
EOF
    systemctl daemon-reload >/dev/null 2>&1 || true
    if systemctl enable --now hls-clean-empty.timer >/dev/null 2>&1; then
        info "empty-segment guard timer active (hls-clean-empty.timer)"
    else
        warn "could not enable hls-clean-empty.timer"
    fi
}

echo -e "${CYAN}── Server tuning: nginx TCP opts · HLS tmpfs · empty-segment guard ──${NC}"
tune_nginx
setup_tmpfs
setup_empty_guard
info "Server tuning complete"
exit 0
